### ISSUE TITLE
How do I get a page id for a random quote?

### ISSUE THREAD

**Issue by retorquere** [fdesjardins/wikiquote#1]

**Comment by fdesjardins** [comment]
You can use the URL for the page you want to pull a quote from. For `https://en.wikiquote.org/wiki/Steve_Jobs` you can use `Steve_Jobs` or `Steve Jobs`.

Another way is to use the `searchPeople` method:
```
wikiquote.searchPeople('steve jobs')
  .then(page => wikiquote.getRandomQuote(page.title))
  .then(quote => console.log(quote)
```
